language: go

go:
    - tip
    - 1.6
    - 1.5
    - 1.4
    - 1.3
    - 1.2
install:
    - go get
    - go get github.com/jarcoal/httpmock
    - go get github.com/onsi/ginkgo
    - go get github.com/onsi/gomega
script:
      - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
      - bash <(curl -s https://codecov.io/bash)
